# version: "3.7"
services:
  caddy:
    # build: ./dockers/caddy
    image: thumperai/caddy:v0.0.5
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      # - "80:80"
    # volumes:
    #   - type: bind
    #     source: './Caddyfile'
    #     target: /etc/caddy/Caddyfile
    #     read_only: true
    #   - ./site:/usr/share/caddy
    #   - ./data:/data
  httpbin:
    image: kennethreitz/httpbin:latest
    container_name: httpbin

    # image: maildev/maildev
    # container_name: maildev


# version: "3.9"
# services:
#   caddy:
#     image: caddy:2.7.2
#     restart: unless-stopped
#     container_name: caddy
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#       - "443:443"
#       - "443:443/udp"
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - ./site:/srv
#       - ./caddy_data:/data
#       - ./caddy_config:/config
#       - ./local:/etc/caddy/auth/local
#     networks:
#       - rp

# networks:
#   rp:
#     name: reverse-proxy
#     external: true 